import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GalleryProvider } from "@/context/galleryContext"; // Import the correct provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GalleryProvider>
          {children}
        </GalleryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
